# Generated by Django 5.0.7 on 2024-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportstaffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
