# Generated by Django 5.0.7 on 2024-07-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportstaffs', '0002_supportcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supportstaffs.supportcategory'),
        ),
        migrations.AlterField(
            model_name='supportcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
