# Generated by Django 5.0.7 on 2024-07-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportstaffs', '0003_supportstaff_type_alter_supportcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportaccounts',
            name='school',
        ),
        migrations.RemoveField(
            model_name='supportaccounts',
            name='status',
        ),
        migrations.AddField(
            model_name='supportaccounts',
            name='accountName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportaccounts',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supportaccounts',
            name='bankName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supportaccounts',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supportstaffs.supportstaff'),
        ),
    ]
