# Generated by Django 5.0.7 on 2024-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportstaffs', '0004_remove_supportaccounts_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportaccounts',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
