# Generated by Django 5.0.7 on 2024-07-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=200)),
                ('idno', models.CharField(max_length=200, unique=True)),
                ('supplierEmail', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('supplierPhone', models.CharField(max_length=200, unique=True)),
                ('supplierAddress', models.CharField(max_length=200)),
                ('supplierWebsite', models.URLField()),
                ('businessName', models.CharField(max_length=200)),
                ('businessRegistrationNumber', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('kra', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('industry', models.CharField(max_length=200)),
                ('productServices', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mpesa', 'Mpesa')], max_length=20)),
                ('bankName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('accountName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('accountNumber', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mpesaName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mpesaNumber', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('openingBalance', models.FloatField(blank=True, null=True)),
                ('paymentInterval', models.CharField(max_length=100)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
