# Generated by Django 5.0.7 on 2024-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_parents_alter_students_health_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='parents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
