# Generated by Django 5.0.7 on 2024-07-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_admission',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.CharField(max_length=150),
        ),
    ]
