# Generated by Django 5.0.7 on 2024-08-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_virtualaccounts_balance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='virtualaccounts',
            table='wallets',
        ),
    ]
