# Generated by Django 5.0.7 on 2024-07-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('parent_idno', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('first_login', models.BooleanField(default=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('parentType', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor')], max_length=10)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'db_table': 'parents',
            },
        ),
    ]
