# Generated by Django 5.0.7 on 2024-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('ref_number', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('tran_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('tran_category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'all_transactions',
            },
        ),
    ]
