# Generated by Django 5.0.7 on 2024-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT'), ('OTHER', 'OTHER')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
