# Generated by Django 5.0.7 on 2024-07-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_transaction_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='tran_ref',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions')),
            ],
        ),
    ]
