# Generated by Django 5.0.7 on 2024-07-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactions_tran_ref_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='file_url',
            field=models.URLField(default=None),
        ),
    ]
