# Generated by Django 5.0.7 on 2024-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_receipts_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], default='SUCCESS', max_length=20),
        ),
        migrations.AlterModelTable(
            name='receipts',
            table='receipts',
        ),
    ]
