# Generated by Django 5.0.7 on 2024-07-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0002_alter_parents_email_alter_parents_phone_number_and_more'),
        ('schools', '0001_initial'),
        ('students', '0005_alter_virtualaccounts_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'db_table': 'fee_category',
            },
        ),
        migrations.CreateModel(
            name='FeeCollections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('DR', 'DR'), ('CR', 'CR')], max_length=10)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('payment_mode', models.CharField(choices=[('virtual_account', 'Virtual Account'), ('Bank_cards', 'Bank Cards'), ('Bank_agent', 'Bank Agent'), ('M-pesa', 'M-pesa'), ('Cash', 'Cash'), ('counter', 'Over the Counter')], max_length=50)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feecategory')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parents')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'db_table': 'fee_collections',
            },
        ),
    ]
