# Generated by Django 5.0.7 on 2024-07-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
        ('students', '0005_alter_virtualaccounts_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStudentBalances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
