# Generated by Django 5.0.7 on 2024-07-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('school_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Ethiopia', 'Ethiopia')], default='Kenya', max_length=50, verbose_name='Country')),
                ('country_code', models.CharField(choices=[('KE', 'KE'), ('UG', 'UG'), ('TZ', 'TZ'), ('DRC', 'DRC'), ('RW', 'RW'), ('SS', 'SS'), ('ET', 'ET')], default='KE', max_length=3, verbose_name='Country Code')),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street_address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone_number1', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(max_length=20)),
                ('phone_number_country_code', models.CharField(choices=[('254', '254'), ('256', '256'), ('255', '255'), ('243', '243'), ('250', '250'), ('211', '211'), ('251', '251')], default='254', max_length=3, verbose_name='Phone Number Country Code')),
                ('email_address', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('school_type', models.CharField(blank=True, choices=[('PRE-PRIMARY', 'pre-primary'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('COLLEGE', 'college'), ('UNIVERSITY', 'university'), ('OTHER', 'Other')], max_length=50)),
                ('boarding_status', models.CharField(blank=True, choices=[('DAY', 'Day'), ('BOARDING', 'Boarding'), ('MIXED', 'Mixed')], max_length=20)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('CDF', 'Congolese Franc'), ('RWF', 'Rwandan Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SSP', 'South Sudanese Pound'), ('ETB', 'Ethiopian Birr')], default='KES', max_length=3, verbose_name='Currency')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('DR', 'Dr'), ('PROF', 'Professor'), ('MS', 'Ms'), ('MX', 'Mx'), ('REV', 'Reverend'), ('SIR', 'Sir'), ('MADAM', 'Madam')], default='Mr', max_length=10)),
                ('designation', models.CharField(choices=[('OWNER', 'School Owner'), ('DIR', 'School Director'), ('FIN', 'Finance Admin'), ('HEAD', 'Headteacher'), ('OTHER', 'Other')], default='OWNER', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='schools.schools')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Ethiopia', 'Ethiopia')], default='Kenya', max_length=50, verbose_name='Country')),
                ('country_code', models.CharField(choices=[('KE', 'KE'), ('UG', 'UG'), ('TZ', 'TZ'), ('DRC', 'DRC'), ('RW', 'RW'), ('SS', 'SS'), ('ET', 'ET')], default='DRC', max_length=3, verbose_name='Country Code')),
                ('county', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_country_code', models.CharField(choices=[('254', '254'), ('256', '256'), ('255', '255'), ('243', '243'), ('250', '250'), ('211', '211'), ('251', '251')], default='254', max_length=3, verbose_name='Phone Number Country Code')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='schools.schools')),
            ],
        ),
    ]
